### ISSUE TITLE
[ENHANCEMENT] Use skypack.dev instead of unkpg.com

### ISSUE THREAD

**Issue by looeee** [looeee/discoverthreejs-site#10]
Load modules from skypack.dev instead of unpkg.com
As per the three.js migration guide, this will have to be done before updating to three.js >=r128.

https://www.skypack.dev/view/three

There are two places that need to be updated: 
[] Anywhere in the text that unpkg.com is mentioned
[] Inside the IDE

In both cases, a simple search and replace should be enough, however, the IDE downloads will need to be tested after making the change.

**Comment by prichodko** [comment]
This may not be needed. 

See: https://twitter.com/mjackson/status/1385800213609152514

**Comment by looeee** [comment]
Thanks, I didn't see that. We would have to update the unpkg links to add the `?`, at least. 

However, if the broader three.js community is moving to skypack, I would still rather follow that.

**Comment by looeee** [comment]
Finally fixed 😅
