### ISSUE TITLE
Can re-initialize git ?

### ISSUE THREAD

**Issue by Xie-Jay** [looeee/discoverthreejs-site#2]
git file size too big because of history include `hugo.exe` 😂

**Comment by looeee** [comment]
Yeah, sorry about that. It should be fixed now - hugo.exe is not included in the project anymore. 

If you're still getting the error try this command (warning: it's slow!):

> git filter-branch --tree-filter 'rm -rf ./hugo.exe' HEAD

**Comment by Xie-Jay** [comment]
> Yeah, sorry about that. It should be fixed now - hugo.exe is not included in the project anymore.
> 
> If you're still getting the error try this command (warning: it's slow!):
> 
> > git filter-branch --tree-filter 'rm -rf ./hugo.exe' HEAD

Thanks

**Comment by Xie-Jay** [comment]
@looeee Oh! May real reason is forget `public` folder

**Comment by looeee** [comment]
No, the public folder is excluded on purpose - it will be built by Hugo. 

I'm sorry for any confusion - I've been reorganizing the repo structure a lot today. I didn't realize it would affect someone else 😅 

I'm nearly finished though. If you can wait for about one hour I will be finished, then you can delete your local version and download a fresh copy. Everything should work smoothly then.

**Comment by Xie-Jay** [comment]
> No, the public folder is excluded on purpose - it will be built by Hugo. I included it by mistake earlier.
> 
> I'm sorry for any confusion - I've been reorganizing the repo structure a lot today. I didn't realize it would affect someone else 😅
> 
> I'm nearly finished though. If you can wait for about one hour I will be finished, then you can delete your local version and download a fresh copy. Everything should work smoothly then.

@looeee Thanks a lot! This book is really easy-to-understand 👍  , so lucky can find it!

**Comment by looeee** [comment]
Thanks, I'm glad you like it ^_^ 

I've finished rearranging folders, does it work for you now? 

Note that you now need the Hugo extended version.

**Comment by looeee** [comment]
Oh, and also I added back the public/ folder to make it easier for me to deploy.

**Comment by Xie-Jay** [comment]
> Oh, and also I added back the public/ folder to make it easier for me to deploy.

@looeee maybe excluded `public` folder would be better, because its size is 134 MB !!!  😂 ,    I test this version but get a error that show miss `postcss` module, I take a PR.

**Comment by looeee** [comment]
> @looeee maybe excluded public folder would be better because its size is 134 MB !!! 😂

It's a good point. I tested this, however, it means I have to build the site on my linux box and that's giving me trouble. So for now it's easier just to include the public/ folder - we can revisit this later if needed.
