### ISSUE TITLE
[BUG, ERROR] SphereBufferGeometry preview appears to be broken

### ISSUE THREAD

**Issue by ahsan-a** [looeee/discoverthreejs-site#22]
**Describe the bug**
On https://discoverthreejs.com/book/first-steps/organizing-with-group/, The first preview box just appears as a gray box with no sphere preview. 

**To Reproduce**
1. Go to https://discoverthreejs.com/book/first-steps/organizing-with-group/#introducing-spherebuffergeometry
2. Look at the gray box and witness the error

**Expected behavior (optional)**
A `SphereBufferGeometry` preview.

**Screenshots**
![image](https://user-images.githubusercontent.com/50714675/123523757-ab895800-d6bd-11eb-9289-7077bfade27d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Version 2009 (Build 19042.1052)
 - Browser: Brave (chromium based)
 - Version 1.26.67 Chromium: 91.0.4472.114 (Official Build) (64-bit)

**Edit**:
Upon progressing through the book, I found [this](https://discoverthreejs.com/book/first-steps/built-in-geometries/#introducing-the-cylinderbuffergeometry) to be broken too.

**Comment by looeee** [comment]
Fixed!
