### ISSUE TITLE
Error in the margins of the website footer

### ISSUE THREAD

**Issue by amruta95** [looeee/discoverthreejs-site#30]
Hi guys! 
Hope you are ding well.
I wanted to let you know that you have an amazing website and I am really inspired by the way it is designed.
I just noticed a slight error in the footer of your website. 

You have given a a margin on the right side of the footer but not on the left side. I have attached an image below. 
Please do have a look.

![image](https://user-images.githubusercontent.com/70916719/135045791-9a785467-1758-4dc6-9e88-43bd79f767a0.png)

**Comment by looeee** [comment]
Hey, thanks for letting me know. Thought I'd fixed that already 😅

**Comment by looeee** [comment]
I've just pushed an update - this should be fixed now (you might need to clear your cache).
