### ISSUE TITLE
Driving example for Three.js

### ISSUE THREAD

**Issue by jrlazz** [looeee/discoverthreejs-site#40]
Hello People,
I made an example of driving an helicopter.
Simple, but good for beginners to control movements with Three.js
I would like your opinion and possible publishing of this work.
Respectfully,
José Roberto Lazzareschi
jrlazz@yahoo.com
example: jrlazz.eu5.org/anim/heli.php

**Comment by looeee** [comment]
Hey @jrlazz it works great, well done! 

If you want more feedback I'd suggest sharing on the forum here:

https://discourse.threejs.org/c/showcase

BTW you'll get more feedback if you share it alongside the code. For example, on codesandbox.io

**Comment by jrlazz** [comment]
Hello,
Thank You very much for the attention of the answer.
José Roberto Lazzareschi

    On Friday, December 10, 2021, 02:11:23 AM GMT-3, Lewy Blue ***@***.***> wrote:  
 
 


Closed #40.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
