### ISSUE TITLE
[BUG, ERROR] Add "precision: 'lowp/mediump/highp'" to renderer

### ISSUE THREAD

**Issue by badde-media** [looeee/discoverthreejs-site#50]
There is a memory allocation error that prevents materials / shaders being drawn on Apple devices and firefox browsers. Gets fixed when adding
```
precision: 'lowp'
```
or
```
precision: 'mediump'
```
or
```
precision: 'highp'
```
to the renderer definition.

**Comment by looeee** [comment]
What pages are showing this error? I'll take a look, although I don't have any apple hardware.

**Comment by looeee** [comment]
Closing as I believe this is an upstream error - if anyone else can reproduce this, please report it to three.js or Apple.
