### ISSUE TITLE
content cant render

### ISSUE THREAD

**Issue by Xie-Jay** [looeee/discoverthreejs-site#7]
[Physically Based Rendering and Lighting](https://discoverthreejs.com/book/first-steps/physically-based-rendering/)

![image](https://user-images.githubusercontent.com/64340763/115828408-43f62880-a440-11eb-855a-05b4267ec912.png)

**Comment by Xie-Jay** [comment]
> This looks fine when I test it, on Chrome and Firefox with windows.
> 
> ![2021-04-23 13_38_09-Physically Based Rendering and Lighting _ Discover three js — Mozilla Firefox](https://user-images.githubusercontent.com/5307958/115829538-4dc85d80-a439-11eb-9f1f-99a7cebb9ef8.png)
> 
> Do you get any error messages in the console? And what browser/OS are you using?

@looeee

![image](https://user-images.githubusercontent.com/64340763/115829747-eb278f80-a441-11eb-949d-0c56ae7db795.png)

chrome  89.0.4389.114

 I try to clear cache, but not work

I run `npm start` and view the site locally, its ok

**Comment by looeee** [comment]
Ah, ok. Can you check on the staging site here and see if it's working:

https://dtjs.lewy.blue/book/first-steps/physically-based-rendering/

**Comment by Xie-Jay** [comment]
> Ah, ok. Can you check on the staging site here and see if it's working:
> 
> https://dtjs.lewy.blue/book/first-steps/physically-based-rendering/

@looeee its ok!

**Comment by looeee** [comment]
OK, great. I'm going to push the updates live later today so it should be fixed then. I'll ping you to check when I have done that.

**Comment by looeee** [comment]
I've pushed the new update live. Can you test it again on discoverthreejs.com? 

If you still see the problem, try emptying your browser cache and check again.

**Comment by Xie-Jay** [comment]
> I've pushed the new update live. Can you test it again on discoverthreejs.com?
> 
> If you still see the problem, try emptying your browser cache and check again.

@looeee thanks,  its ok now
